### ISSUE TITLE
mate cli doesnt work from inside the models folder

### ISSUE THREAD

**Issue by SalamanderXing** [ilex-paraguariensis/yerbamate#27]
From inside the models folder:
`Traceback (most recent call last):
  File "/home/bluesk/miniconda3/envs/extended-gan/bin/mate", line 5, in <module>
    mate_cli.main()
  File "/home/bluesk/miniconda3/envs/extended-gan/lib/python3.9/site-packages/yerbamate/mate_cli.py", line 85, in main
    mate = Mate()
  File "/home/bluesk/miniconda3/envs/extended-gan/lib/python3.9/site-packages/yerbamate/mate.py", line 24, in __init__
    self.__findroot()
  File "/home/bluesk/miniconda3/envs/extended-gan/lib/python3.9/site-packages/yerbamate/mate.py", line 57, in __findroot
    self.__load_mate_config(os.path.join(os.getcwd(), "mate.json"))
  File "/home/bluesk/miniconda3/envs/extended-gan/lib/python3.9/site-packages/yerbamate/mate.py", line 43, in __load_mate_config
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bluesk/Documents/amex/amex/mate.json'`

**Comment by SalamanderXing** [comment]
Fixed.
